export default [
  {
    key: "img1",
    thumb: require("../assets/img1.png"),
    tiles: {
      0: require("../assets/tiles/img1/0.png"),
      1: require("../assets/tiles/img1/1.png"),
      2: require("../assets/tiles/img1/2.png"),
      3: require("../assets/tiles/img1/3.png"),
      4: require("../assets/tiles/img1/4.png"),
      5: require("../assets/tiles/img1/5.png"),
      6: require("../assets/tiles/img1/6.png"),
      7: require("../assets/tiles/img1/7.png"),
    },
  },
  {
    key: "img2",
    thumb: require("../assets/img2.png"),
    tiles: {
      0: require("../assets/tiles/img2/0.png"),
      1: require("../assets/tiles/img2/1.png"),
      2: require("../assets/tiles/img2/2.png"),
      3: require("../assets/tiles/img2/3.png"),
      4: require("../assets/tiles/img2/4.png"),
      5: require("../assets/tiles/img2/5.png"),
      6: require("../assets/tiles/img2/6.png"),
      7: require("../assets/tiles/img2/7.png"),
    },
  },
  {
    key: "img3",
    thumb: require("../assets/img3.png"),
    tiles: {
      0: require("../assets/tiles/img3/0.png"),
      1: require("../assets/tiles/img3/1.png"),
      2: require("../assets/tiles/img3/2.png"),
      3: require("../assets/tiles/img3/3.png"),
      4: require("../assets/tiles/img3/4.png"),
      5: require("../assets/tiles/img3/5.png"),
      6: require("../assets/tiles/img3/6.png"),
      7: require("../assets/tiles/img3/7.png"),
    },
  },
  {
    key: "img4",
    thumb: require("../assets/img4.png"),
    tiles: {
      0: require("../assets/tiles/img4/0.png"),
      1: require("../assets/tiles/img4/1.png"),
      2: require("../assets/tiles/img4/2.png"),
      3: require("../assets/tiles/img4/3.png"),
      4: require("../assets/tiles/img4/4.png"),
      5: require("../assets/tiles/img4/5.png"),
      6: require("../assets/tiles/img4/6.png"),
      7: require("../assets/tiles/img4/7.png"),
    },
  },
  {
    key: "img5",
    thumb: require("../assets/img5.png"),
    tiles: {
      0: require("../assets/tiles/img5/0.png"),
      1: require("../assets/tiles/img5/1.png"),
      2: require("../assets/tiles/img5/2.png"),
      3: require("../assets/tiles/img5/3.png"),
      4: require("../assets/tiles/img5/4.png"),
      5: require("../assets/tiles/img5/5.png"),
      6: require("../assets/tiles/img5/6.png"),
      7: require("../assets/tiles/img5/7.png"),
    },
  },
  {
    key: "img6",
    thumb: require("../assets/img6.png"),
    tiles: {
      0: require("../assets/tiles/img6/0.png"),
      1: require("../assets/tiles/img6/1.png"),
      2: require("../assets/tiles/img6/2.png"),
      3: require("../assets/tiles/img6/3.png"),
      4: require("../assets/tiles/img6/4.png"),
      5: require("../assets/tiles/img6/5.png"),
      6: require("../assets/tiles/img6/6.png"),
      7: require("../assets/tiles/img6/7.png"),
    },
  },
  {
    key: "img7",
    thumb: require("../assets/img7.png"),
    tiles: {
      0: require("../assets/tiles/img7/0.png"),
      1: require("../assets/tiles/img7/1.png"),
      2: require("../assets/tiles/img7/2.png"),
      3: require("../assets/tiles/img7/3.png"),
      4: require("../assets/tiles/img7/4.png"),
      5: require("../assets/tiles/img7/5.png"),
      6: require("../assets/tiles/img7/6.png"),
      7: require("../assets/tiles/img7/7.png"),
    },
  },
  {
    key: "img8",
    thumb: require("../assets/img8.png"),
    tiles: {
      0: require("../assets/tiles/img8/0.png"),
      1: require("../assets/tiles/img8/1.png"),
      2: require("../assets/tiles/img8/2.png"),
      3: require("../assets/tiles/img8/3.png"),
      4: require("../assets/tiles/img8/4.png"),
      5: require("../assets/tiles/img8/5.png"),
      6: require("../assets/tiles/img8/6.png"),
      7: require("../assets/tiles/img8/7.png"),
    },
  },
  {
    key: "img9",
    thumb: require("../assets/img9.png"),
    tiles: {
      0: require("../assets/tiles/img9/0.png"),
      1: require("../assets/tiles/img9/1.png"),
      2: require("../assets/tiles/img9/2.png"),
      3: require("../assets/tiles/img9/3.png"),
      4: require("../assets/tiles/img9/4.png"),
      5: require("../assets/tiles/img9/5.png"),
      6: require("../assets/tiles/img9/6.png"),
      7: require("../assets/tiles/img9/7.png"),
    },
  },
];

